In [0]:
from google.colab import files

In [0]:
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import io

In [0]:
df = pd.read_csv(io.BytesIO(uploaded['train.csv']))

In [0]:
df.head()

name gender
0       Mary      F
1       Anna      F
2       Emma      F
3  Elizabeth      F
4     Minnie      F

In [0]:
df.gender.value_counts()

F    39445
M    20555
Name: gender, dtype: int64

In [0]:
df.gender.value_counts()/len(df)

F    0.657417
M    0.342583
Name: gender, dtype: float64

In [0]:
x = df.name

In [0]:
x

0             Mary
1             Anna
2             Emma
3        Elizabeth
4           Minnie
           ...    
59995      Kenyari
59996        Kewin
59997      Khachik
59998      Khaleed
59999       Laredo
Name: name, Length: 60000, dtype: object

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
cv = TfidfVectorizer()

In [0]:
X = cv.fit_transform(x)

In [0]:
X

<60000x60000 sparse matrix of type '<class 'numpy.float64'>'
	with 60000 stored elements in Compressed Sparse Row format>

In [0]:
y = df.gender

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [0]:
x_train

<45000x60000 sparse matrix of type '<class 'numpy.float64'>'
	with 45000 stored elements in Compressed Sparse Row format>

In [0]:
x_test

<15000x60000 sparse matrix of type '<class 'numpy.float64'>'
	with 15000 stored elements in Compressed Sparse Row format>

In [0]:
from sklearn.svm import SVC

In [0]:
clf = SVC()

In [0]:
clf.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = clf.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [0]:
confusion_matrix(y_test,y_pred)

array([[9871,    0],
       [5129,    0]])

In [0]:
accuracy_score(y_test,y_pred)

0.6580666666666667

In [0]:
print(classification_report(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           F       0.66      1.00      0.79      9871
           M       0.00      0.00      0.00      5129

    accuracy                           0.66     15000
   macro avg       0.33      0.50      0.40     15000
weighted avg       0.43      0.66      0.52     15000



In [0]:
sample_name =['karthik']

In [0]:
vct  = cv.transform(sample_name)

In [0]:
vct

<1x60000 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [0]:
clf.predict(vct)

array(['F'], dtype=object)

In [0]:
name = ['aditya']

In [0]:
vct = cv.transform(name).toarray()

In [0]:
clf.predict(vct)

array(['F'], dtype=object)

In [0]:
vct

array([[0., 0., 0., ..., 0., 0., 0.]])

Feature Extraction 


In [0]:
df['first_letter'] = df.name.str[0]

In [0]:
df['last_letter'] = df.name.str[-1]

In [0]:
df['two_last_letters'] = df.name.str[-2:]

In [0]:
df['two_first_letters'] = df.name.str[0:2]

In [0]:
df.head()

name gender first_letter last_letter two_last_letters two_first_letters
0       Mary      F            M           y               ry                Ma
1       Anna      F            A           a               na                An
2       Emma      F            E           a               ma                Em
3  Elizabeth      F            E           h               th                El
4     Minnie      F            M           e               ie                Mi

In [0]:
x = df.drop('gender',axis=1)

In [0]:
x

name first_letter last_letter two_last_letters two_first_letters
0           Mary            M           y               ry                Ma
1           Anna            A           a               na                An
2           Emma            E           a               ma                Em
3      Elizabeth            E           h               th                El
4         Minnie            M           e               ie                Mi
...          ...          ...         ...              ...               ...
59995    Kenyari            K           i               ri                Ke
59996      Kewin            K           n               in                Ke
59997    Khachik            K           k               ik                Kh
59998    Khaleed            K           d               ed                Kh
59999     Laredo            L           o               do                La

[60000 rows x 5 columns]

In [0]:
y = df.gender

In [0]:
y

0        F
1        F
2        F
3        F
4        F
        ..
59995    M
59996    M
59997    M
59998    M
59999    M
Name: gender, Length: 60000, dtype: object

##TfidVectorizer

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
tfidf = TfidfVectorizer()

In [0]:
x.values.tolist()

[['Mary', 'M', 'y', 'ry', 'Ma'],
 ['Anna', 'A', 'a', 'na', 'An'],
 ['Emma', 'E', 'a', 'ma', 'Em'],
 ['Elizabeth', 'E', 'h', 'th', 'El'],
 ['Minnie', 'M', 'e', 'ie', 'Mi'],
 ['Margaret', 'M', 't', 'et', 'Ma'],
 ['Ida', 'I', 'a', 'da', 'Id'],
 ['Alice', 'A', 'e', 'ce', 'Al'],
 ['Bertha', 'B', 'a', 'ha', 'Be'],
 ['Sarah', 'S', 'h', 'ah', 'Sa'],
 ['Annie', 'A', 'e', 'ie', 'An'],
 ['Clara', 'C', 'a', 'ra', 'Cl'],
 ['Ella', 'E', 'a', 'la', 'El'],
 ['Florence', 'F', 'e', 'ce', 'Fl'],
 ['Cora', 'C', 'a', 'ra', 'Co'],
 ['Martha', 'M', 'a', 'ha', 'Ma'],
 ['Laura', 'L', 'a', 'ra', 'La'],
 ['Nellie', 'N', 'e', 'ie', 'Ne'],
 ['Grace', 'G', 'e', 'ce', 'Gr'],
 ['Carrie', 'C', 'e', 'ie', 'Ca'],
 ['Maude', 'M', 'e', 'de', 'Ma'],
 ['Mabel', 'M', 'l', 'el', 'Ma'],
 ['Bessie', 'B', 'e', 'ie', 'Be'],
 ['Jennie', 'J', 'e', 'ie', 'Je'],
 ['Gertrude', 'G', 'e', 'de', 'Ge'],
 ['Julia', 'J', 'a', 'ia', 'Ju'],
 ['Hattie', 'H', 'e', 'ie', 'Ha'],
 ['Edith', 'E', 'h', 'th', 'Ed'],
 ['Mattie', 'M', 'e', 'ie', 'Ma'],

In [0]:
x = x.applymap(str.lower)

In [0]:
x_arr = x.values.tolist()

In [0]:
x_arr

[['mary', 'm', 'y', 'ry', 'ma'],
 ['anna', 'a', 'a', 'na', 'an'],
 ['emma', 'e', 'a', 'ma', 'em'],
 ['elizabeth', 'e', 'h', 'th', 'el'],
 ['minnie', 'm', 'e', 'ie', 'mi'],
 ['margaret', 'm', 't', 'et', 'ma'],
 ['ida', 'i', 'a', 'da', 'id'],
 ['alice', 'a', 'e', 'ce', 'al'],
 ['bertha', 'b', 'a', 'ha', 'be'],
 ['sarah', 's', 'h', 'ah', 'sa'],
 ['annie', 'a', 'e', 'ie', 'an'],
 ['clara', 'c', 'a', 'ra', 'cl'],
 ['ella', 'e', 'a', 'la', 'el'],
 ['florence', 'f', 'e', 'ce', 'fl'],
 ['cora', 'c', 'a', 'ra', 'co'],
 ['martha', 'm', 'a', 'ha', 'ma'],
 ['laura', 'l', 'a', 'ra', 'la'],
 ['nellie', 'n', 'e', 'ie', 'ne'],
 ['grace', 'g', 'e', 'ce', 'gr'],
 ['carrie', 'c', 'e', 'ie', 'ca'],
 ['maude', 'm', 'e', 'de', 'ma'],
 ['mabel', 'm', 'l', 'el', 'ma'],
 ['bessie', 'b', 'e', 'ie', 'be'],
 ['jennie', 'j', 'e', 'ie', 'je'],
 ['gertrude', 'g', 'e', 'de', 'ge'],
 ['julia', 'j', 'a', 'ia', 'ju'],
 ['hattie', 'h', 'e', 'ie', 'ha'],
 ['edith', 'e', 'h', 'th', 'ed'],
 ['mattie', 'm', 'e', 'ie', 'ma'],

In [0]:
x_mod = []
for i in x_arr:
  x_mod.append(' '.join(i))

In [0]:
x_mod

['mary m y ry ma',
 'anna a a na an',
 'emma e a ma em',
 'elizabeth e h th el',
 'minnie m e ie mi',
 'margaret m t et ma',
 'ida i a da id',
 'alice a e ce al',
 'bertha b a ha be',
 'sarah s h ah sa',
 'annie a e ie an',
 'clara c a ra cl',
 'ella e a la el',
 'florence f e ce fl',
 'cora c a ra co',
 'martha m a ha ma',
 'laura l a ra la',
 'nellie n e ie ne',
 'grace g e ce gr',
 'carrie c e ie ca',
 'maude m e de ma',
 'mabel m l el ma',
 'bessie b e ie be',
 'jennie j e ie je',
 'gertrude g e de ge',
 'julia j a ia ju',
 'hattie h e ie ha',
 'edith e h th ed',
 'mattie m e ie ma',
 'rose r e se ro',
 'catherine c e ne ca',
 'lillian l n an li',
 'ada a a da ad',
 'lillie l e ie li',
 'helen h n en he',
 'jessie j e ie je',
 'louise l e se lo',
 'ethel e l el et',
 'lula l a la lu',
 'myrtle m e le my',
 'eva e a va ev',
 'frances f s es fr',
 'lena l a na le',
 'lucy l y cy lu',
 'edna e a na ed',
 'maggie m e ie ma',
 'pearl p l rl pe',
 'daisy d y sy da',
 'fannie f e ie fa',


In [0]:
x_vect = tfidf.fit_transform(x_mod)

In [0]:
x_vect

<60000x60357 sparse matrix of type '<class 'numpy.float64'>'
	with 179494 stored elements in Compressed Sparse Row format>

In [0]:
y.shape

(60000,)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x_vect,y,test_size=0.3)

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
clf = RandomForestClassifier()

In [0]:
clf.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_predict  = clf.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [0]:
confusion_matrix(y_test,y_predict)

array([[10601,  1162],
       [ 2383,  3854]])

In [0]:
accuracy_score(y_test,y_predict)

0.8030555555555555

In [0]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           F       0.82      0.90      0.86     11763
           M       0.77      0.62      0.68      6237

    accuracy                           0.80     18000
   macro avg       0.79      0.76      0.77     18000
weighted avg       0.80      0.80      0.80     18000



In [0]:
clf.feature_importances_

array([4.29207421e-04, 0.00000000e+00, 2.68617726e-05, ...,
       0.00000000e+00, 0.00000000e+00, 1.84514544e-04])

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
param = {
    'criterion':['gini','entropy'],
    'max_depth': [10, 20, 30, 40, 50],
    'max_features': ['auto', 'sqrt'],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10],
    'n_estimators': [50,100,150,200]
}

In [0]:
grid = GridSearchCV(estimator=clf,param_grid=param,n_jobs=-1)

In [0]:
grid.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
